accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('likelist/<str:username>/', views.likelist, name='likelist'),
    path('search/', views.search, name='search'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    released_date = models.DateField()
    popularity = models.FloatField()
    vote_avg = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name',)


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name',)

accounts/views.py
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import redirect, render
from django.contrib.auth import get_user_model
from django.http import JsonResponse

from .forms import CustomUserChangeForm, CustomUserCreationForm


# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            # 로그인
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('movies:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
        
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def delete(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            request.user.delete()
            auth_logout(request)
    return redirect('movies:index')


def update(request):
    if request.method == 'POST':    
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


def follow(request, user_pk):
    if request.user.is_authenticated:
        User = get_user_model()
        me = request.user
        you = User.objects.get(pk=user_pk)
        if me != you:
            if you.followers.filter(pk=me.pk).exists():
                you.followers.remove(me)
                # flag 만들어서 언팔로우됐다고 알려주고
                is_followed = False
            else:
                you.followers.add(me)
                # flag 만들어서 팔로우됐다고 알려주고
                is_followed = True
            # context -> flag 담아서
            context = {
                'is_followed': is_followed, # True or False
                'followers_count': you.followers.count(),
                'followings_count': you.followings.count(),
            }
            # JsonResponse에 담아서 return
            return JsonResponse(context)
        return redirect('accounts:profile', you.username)
    return redirect('accounts:login')

movies/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Movie
from django.http import JsonResponse
from django.contrib.auth import get_user_model


# Create your views here.
def index(request):
    if request.user.is_authenticated:
        movies = Movie.objects.all()
        context = {
            'movies': movies,
        }
        return render(request, 'movies/index.html', context)
    return redirect('accounts:login')


def detail(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)
        context = {
            'movie': movie,
        }
        return render(request, 'movies/detail.html', context)
    return redirect('accounts:login')


def search(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            searched = request.POST['search']
            User = get_user_model()
            users = User.objects.filter(username__contains=searched)
            movies = Movie.objects.filter(title__contains=searched)
            return render(request, 'movies/search.html', {'searched': searched, 'movies': movies, 'users': users,})
        return render(request, 'movies/search.html')
    return redirect('accounts:login')


def like(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)

        if movie.like_users.filter(pk=request.user.pk).exists():
            # 좋아요 취소
            movie.like_users.remove(request.user)
            liked = False
        else:
            # 좋아요 누름
            movie.like_users.add(request.user)
            liked = True

        data = {
            'liked':liked,
            'like_count':movie.like_users.count(),
        }
        return JsonResponse(data)
    return redirect('accounts:login')


def likelist(request, username):
    if request.user.is_authenticated:
        User = get_user_model()
        person = User.objects.get(username=username)
        context = {
            'person': person,
        }
        return render(request, 'movies/likelist.html', context)
    return redirect('accounts:login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
<link rel="stylesheet" href="{% static './css/change_password.css' %}">

<div class="out-layer">
  <br>
  <form class="change-password-form" action="{% url 'accounts:change_password' %}" method="POST">
      <h1 class="title-change-password">비밀번호 변경</h1>
      <br>
      {% csrf_token %}
      {{ form.as_p }}
      <div class="button-change-password">
        <button type="submit" class="btn btn-dark">비밀번호 변경</button>
        <a href="{% url 'accounts:update' %}" class="btn btn-outline-dark" style="font-family: 'Hanna', sans-serif;">뒤로가기</a>
      </div>
    </form>
  </div>  
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}


{% block content %}
<link rel="stylesheet" href="{% static './css/login.css' %}">
<div class="out-layer" >
  <div class="login-div">
    <div>
      <h1 class="title-login">로그인</h1>
    </div>
  <br>
  <div>
    <form action="" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <br>
      <div class="button-login">
        <button type="submit" class="btn btn-outline-dark btn-block btn-large">로그인</button>
        <a href="{% url 'accounts:signup' %}" class="btn btn-dark">회원가입</a>
      </div>
    </form>
  </div>
</div>
  {% bootstrap_css %}
  {% bootstrap_javascript %}
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
<link rel="stylesheet" href="{% static './css/profile.css' %}">

<div class="out-layer">
  <div class="profile-div">
    <h2 class="title-profile">{{ person.last_name }}{{person.first_name }}님의 프로필</h1>
    <br>
    <div class="follow-div">
      팔로워 :<span id="followers-count">{{ person.followers.all|length }}</span><br>
      팔로잉 :<span id="followings-count">{{ person.followings.all|length }}<span>
    </div>
    <br>

    {% if request.user != person %}
    <div>
      <form id="follow-form" data-user-id={{ person.pk }}>
        {% csrf_token %}
        {% if request.user in person.followers.all %}
        <button type="submit" class="btn btn-outline-dark btn-block btn-large" style="font-family: 'Hanna', sans-serif;">언팔로우</button>
        {% else %}
        <button type="submit" class="btn btn-outline-dark btn-block btn-large" style="font-family: 'Hanna', sans-serif;">팔로우</button>
        {% endif %}
      </form>
      {% endif %}
      
      <hr>
      <h2 class="text-profile">{{ person.last_name }}{{person.first_name }}님이 좋아하는 영화</h2>
      <br>
      <div class='container'>
        {% for movie in person.like_movies.all %}
        <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" class="rounded" onclick="location.href='{% url 'movies:detail' movie.pk %}'">
        {% endfor %}
        
      </div>
      <br>
    {% if request.user == person %}
    <button type="button" class="btn btn-outline-dark" style="font-family: 'Hanna', sans-serif;" onclick="location.href='/accounts/update/'">정보 수정</button>
    <form action="{% url 'accounts:delete' %}" method="POST" class="float-end">
      {% csrf_token %}
      <button type="submit" style="font-family: 'Hanna', sans-serif;" class="btn btn-danger">회원 탈퇴</button>
    </form>
    {% endif %}
    <button type="button" class="btn btn-dark" style="font-family: 'Hanna', sans-serif;" onclick="location.href={% url 'movies:index' %}">뒤로 가기</button>
    </div>
  </div>
</div>
  
{% endblock content %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const form = document.querySelector('#follow-form')
    form.addEventListener('submit', function (event) {
      event.preventDefault()
      const userId = event.target.dataset.userId
      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

      axios({
        method: 'post',
        url: `/accounts/${userId}/follow/`,
        headers: {'X-CSRFToken': csrftoken},

      })
      .then((response) => {
        const isFollowed = response.data.is_followed
        const followBtn = document.querySelector('#follow-form > button[type=submit]')

        if (isFollowed === true) {
          followBtn.innerText = '언팔로우'
        } else {
          followBtn.innerText = '팔로우'
        }
        
        const followersCountTag = document.querySelector('#followers-count')
        const followingsCountTag = document.querySelector('#followings-count')

        const followersCount = response.data.followers_count
        const followingsCount = response.data.followings_count
        followersCountTag.innerText = followersCount 
        followingsCountTag.innerText = followingsCount
        })
        .catch((error) => {
          console.log(error)
        })
    })
  </script>


{% endblock script %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}

<link rel="stylesheet" href="{% static './css/signup.css' %}">
<div class="out-layer">
  <div class="signup-div">
    <h1 class="title-signup">회원가입</h1>
    <br>
    <form action="{% url 'accounts:signup' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form layout='inline' %}
        <br>
        <div style="text-align: center;">
          <button type="submit" class="btn btn-outline-dark btn-block btn-large float-start" style="font-family: 'Hanna', sans-serif;">회원가입</button>
          <button type="button" class="btn btn-dark float-end" style="font-family: 'Hanna', sans-serif;" onclick="location.href={% url 'movies:index' %}">뒤로 가기</button>
        </div>
    </form>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
<br>
<link rel="stylesheet" href="{% static './css/update.css' %}">
<div class="out-layer">
  <br>
  <form class="update-div" action="{% url 'accounts:update' %}" method="POST">
    <h1 class="title-update">회원정보수정</h1>
    <br>
    {% csrf_token %}
    {{ form.as_p }}
    <br>
    <div class="button-update">
      <button type="submit" class="btn btn-dark">수정</button>
      <a href="{% url 'accounts:profile' user %}" class="btn btn-outline-dark" style="font-family: 'Hanna', sans-serif;">뒤로가기</a>
    </div>
  </form>
</div>  
{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
<br>
<div class="background">
  
  <div class="movie-title">
    <h1>{{ movie.title }}</h1>
  </div> 
  
  <div class="flex-container">
    
    <div class="flex-item1">
      <img src="https://image.tmdb.org/t/p/original{{ movie.poster_path }}" class="card-img" alt="{{ movie.name }}">
    </div>
    
    <div class="flex-item2">
      
      <div class="div-title">
        <p>개봉일</p>
      </div>
      <div class="div-content">
        <p>{{ movie.released_date }}</p>
      </div>
      <br>
      
      <div class="div-title">
        <p>관객</p>
      </div>
      <div class="div-content">
        <p>{{ movie.popularity }}명</p>
      </div>
      <br>
      
      
      <div class="div-title">
        <p>평점(10점 만점)</p>
      </div>
      <div class="div-content">
        <p>{{ movie.vote_avg }}점</p>
      </div>
      <br>
      
      
      <div class="div-title">
        <p>개요</p>
      </div>
      <div class="div-content">
        <p>{{ movie.overview }}</p>
      </div>
      <br>

      <img src="{{ movie.poster_path }}" alt="">
      
      <div class="like">
        <form class="like-form" data-movie-id="{{ movie.pk }}">
          {% csrf_token %}
          {% if request.user in movie.like_users.all %}
          <button id="like-{{ movie.pk }}" class="btn btn-outline-dark">♥ LIKE</button>

          {% else %}
          <button id="like-{{ movie.pk }}" class="btn btn-outline-dark">♡ LIKE</button>

          {% endif %}
        </form>
        <p>
          <span id="like-count-{{ movie.pk }}">{{ movie.like_users.all|length }}</span>명이 이 영화를 좋아합니다.
        </p>
      </div>
    </div>
  </div>
</div>
  
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const forms = document.querySelectorAll('.like-form')
    forms.forEach((form) => {
      form.addEventListener('submit', function(event) {
        
        event.preventDefault()
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
        const movieId = form.dataset.movieId
        const requestUrl = `http://127.0.0.1:8000/movies/${movieId}/like/`
        const config = {
          headers: {'X-CSRFToken': csrftoken},
          }

        axios.post(requestUrl, {}, config)
        .then((res) => {
          const liked = res.data.liked
          const likeBtn = document.querySelector(`#like-${movieId}`)
          const likeCount = document.querySelector(`#like-count-${movieId}`)

          likeBtn.innerText = liked? '♥ LIKE' : '♡ LIKE'

          likeCount.innerText = res.data.like_count
        })
        .catch((err) => {
          console.error(err)
        })
      })
    })
  </script>
{% endblock content %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

{% endblock script %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
<link rel="stylesheet" href="{% static './css/detail.css' %}">

<br>
<h1 class="title-index" style="font-family: 'Hanna', sans-serif;">전체 영화</h1>
<div class="contain d-flex flex-wrap justify-content-center">
{% for movie in movies %}
  <a href="{% url 'movies:detail' movie.pk %}">
    <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" class="rounded main_img" alt="...">
  </a>
{% endfor %}
</div>
{% endblock content %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
{% endblock script %}

movies/templates/movies/likelist.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
<link rel="stylesheet" href="{% static './css/likelist.css' %}">

<br>
<h1 class="list-follow">{{ person.last_name }}{{person.first_name }}님의 팔로우 목록</h1>
<div class="container">
  <div class="row">
{% for follow in person.followings.all %}
  <a href="{% url 'accounts:profile' follow %}" style='text-align: center; text-decoration: none;'>
  {{ follow.username}}
  </a>
{% endfor %}
  </div>
</div>
<br>
<hr>

<h1 class="list-like">{{ person.last_name }}{{person.first_name }}님이 좋아하는 영화 목록</h1>
<div class="container d-flex flex-wrap" id='total'>
{% for movie in person.like_movies.all %}
  <a href="{% url 'movies:detail' movie.pk %}">
    <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" class="rounded like_img" alt="...">
  </a>
{% endfor %}
</div>

{% endblock content %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
{% endblock script %}

movies/templates/movies/search.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
<link rel="stylesheet" href="{% static './css/search.css' %}">
  <br>
  <div class="container">
    <h1 class="title-search">통합 검색창</h1>
    <br>
    <div class="d-flex flex-colum justify-content-center">
      <form action="{% url 'movies:search' %}" method='POST'>
        {% csrf_token %}
        <div class="row">
          <input type="search" class="form-control me-2" name="search" placeholder='아이디 or 영화 제목 검색'>
          <button type="submit" class="btn btn-dark">검색</button>
        </form>
      </div>
    </div>
  </div>
  <br>
  <br>


  {% if searched %}
  <h1 class="title-userlist">유저 목록</h1>
  {% if not users %}
    <br>
    <p style='text-align: center;'>검색 결과가 없습니다.</p>
  {% else %}
  
  <div class="container">
    <div class="row">
      {% for user in users %}
      <a href="{% url 'accounts:profile' user %}" class="username">
        {{ user.username }}
      </a>
      {% endfor %}
    </div>
  </div>



  {% endif %}
  <br>
  <br>
  <h1 class="title-movielist">영화 목록</h1>
  <br>
  {% if not movies %}
    <p class="nosearch">검색 결과가 없습니다.</p>
  {% else %}

    <div class="contain d-flex flex-wrap justify-content-center" id='total'>
      {% for movie in movies %}
      <a href="{% url 'movies:detail' movie.pk %}">
        <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" class="rounded main_img" alt="...">
      </a>
      {% endfor %}
    </div>
    {% endif %}
  {% endif %}
{% endblock content %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>

</script>
{% endblock script %}

templates/_nav.html
{% load static %}
{% load django_bootstrap5 %}


{% if user.is_authenticated %}
<link rel="stylesheet" href="{% static 'css/_nav.css' %}">
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'movies:index' %}">
      <img src="/static/img/MOVIE_PEDIA_logo.png" alt="MOVIE PEDIA" class="logo">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center container" id="navbarNav">
      <ul class="navbar-nav row">
        <li class="nav-item col-3">
          <a href="{% url 'movies:index' %}">
            <img src="/static/img/home.png" alt="home" class='logo'>
          </a>
        </li>
        <li class="nav-item col-3">
          <a href="{% url 'movies:likelist' user%}">
            <img src="/static/img/heart.png" alt="like" class='logo'>
          </a>
        </li>
        <li class="nav-item col-3">
          <a href="{% url 'movies:search' %}">
            <img src="/static/img/search.png" alt="search" class='logo'>
          </a>
        </li>
      </ul>
    </div>
    <div>
      <a href="{% url 'accounts:profile' user %}" class="btn btn-outline-dark" style="font-family: 'Hanna', sans-serif;">프로필</a>
      <a href="{% url 'accounts:logout' %}" class="btn btn-dark" style="font-family: 'Hanna', sans-serif;">로그아웃</a>
{% endif %}
    </div>
  </div>
</nav>

templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Document</title>

  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
  
  {% include '_nav.html' %}
  {% comment %} <hr> {% endcomment %}
  <div class="contanier justify-content-center">
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock script %}  

<style>

</style>

</body>
</html>